# Generated by Django 4.1.3 on 2022-12-14 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catagory',
            old_name='carnumber',
            new_name='number',
        ),
        migrations.RemoveField(
            model_name='catagory',
            name='carowner',
        ),
    ]
