# Generated by Django 4.1.3 on 2022-12-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suba', '0002_rename_carnumber_catagory_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagory',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
