# Generated by Django 4.1.3 on 2022-12-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suba', '0003_catagory_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='status',
            field=models.BooleanField(default=False, help_text='0-show,1-hidden'),
        ),
    ]
